### ISSUE TITLE
The submission status always show "error"?

### ISSUE THREAD

**Issue by wdhudiekou** [aasharma90/Unprocessing_for_RAW_Denoising#1]
Hello, thank you very much for sharing. Have you ever tried to submit results to Darmstadt Noise Dataset? Why is my submission status always showing errors?

**Comment by aasharma90** [comment]
Hi @wdhudiekou, 

Sorry, I've not tried submitting the results to the Darmstadt site. My implementation is more into visualization of the denoised results, and hence, might not be generating the results in the submission-needed format. Kindly look into the official Tensorflow implementation and see how the results are generated for official submission. 

Hope it helps!

**Comment by xiaoxiaowannote** [comment]
hello! can you show me a DND datasets from google drive?  thanks!
