### ISSUE TITLE
The clean sRGB image?

### ISSUE THREAD

**Issue by jsliu17** [aasharma90/Unprocessing_for_RAW_Denoising#3]
Hi, thank you very much for your work! but I have a question that I  downloaded the Darmstadt Noise Dataset in the official website, but I found it only has noisy raw image and noisy srgb image, where to download  the clean rgb image?  looking forward to your reply!

**Comment by aasharma90** [comment]
Hi @jsliu17 

Unfortunately, the dataset does not come with the clean sRGB images. For the same reason, we cannot perform any quantitative evaluation at our ends, and the only way it is done is through official submission on their evaluation webpage.

Hope it helps!

**Comment by xiaoxiaowannote** [comment]
> 

hello , can you send me a google dirve link of the dnd datasets ,thanks!
