### ISSUE TITLE
checkpoint_ 400. Tar decompression failed. Thank you for providing a new one

### ISSUE THREAD

**Issue by jhfmat** [aasharma90/Unprocessing_for_RAW_Denoising#7]
checkpoint_ 400. Tar decompression failed. Thank you for providing a new one

**Comment by aasharma90** [comment]
Hi @jhfmat 

Could you please elaborate on the problem you are facing? Couldn't find any issues with the pre-trained checkpoint provided in the repo.

**Comment by jhfmat** [comment]
hi aasharma90
Failed to download the trained model and decompress it

**Comment by aasharma90** [comment]
Not sure why it needs to be decompressed. 

Could you show me the output of the following code? Please make sure you download the checkpoint first and place it in your current directory. 

` import torch`

`model_state_dict = torch.load('./checkpoint_400.tar')['state_dict']`
`model.load_state_dict(model_state_dict)`

If you are able to run the above code without any errors, the checkpoint is working just fine. In that case, please revisit the test code, try running it again and let me know if you face any further issues.

**Comment by aasharma90** [comment]
Closing the issue due to inactivity. @jhfmat, feel free to re-open the issue if needed. 

Thanks!
