### ISSUE TITLE
Can I use png images instead of mat？

### ISSUE THREAD

**Issue by hzy-del** [aasharma90/Unprocessing_for_RAW_Denoising#8]

**Comment by aasharma90** [comment]
Hi, yes, it should be possible. Just change the data loading part (lines 76-77 in `dnd_denoise.py`) to read your images which you can do by either using `cv2` or `PIL`

**Comment by chaow94** [comment]
Hi, I notice model's input is **input_img** and **input_variance**, and 

`variance = shot_noise * noisy_img + read_noise
`

However, we can't get shot_noise and read_noise in the real world, so how to infer in pure RGB or RAW?
